# Generate Heatmaps Failing

## Tags

* type: bug
* status: open
* priority: medium
* assigned: fredm, zachs, zsloan
* keywords: genenetwork3, gn3, GN3, heatmaps

## Reproduce

* Go to https://genenetwork.org/
* Under "Select and Search" menu, enter "synap*" for the "Get Any" field
* Click "Search"
* In search results page, select first 10 traits
* Click "Add"
* Under "Create a new collection" enter the name "newcoll" and click "Create collection"
* In the collections page that shows up, click "Select All" once
* Ensure all the traits are selected
* Click "Generate Heatmap" and wait
* Note how system fails silently with no heatmap presented

### Notes

On https://gn2-fred.genenetwork.org the heatmaps fails with a note ("ERROR: undefined"). In the logs, I see "Module 'scipy' has no attribute 'array'" which seems to be due to a change in numpy.
=> https://github.com/MaartenGr/BERTopic/issues/1791
=> https://github.com/scipy/scipy/issues/19972

This issue should not be present with python-plotly@5.20.0 but since guix-bioinformatics pins the guix version to `b0b988c41c9e0e591274495a1b2d6f27fcdae15a`, we are not able to pull in newer versions of packages from guix.
